version: '3'

services:
  convergencebackend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  tradingbackend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080"

networks:
  default:
    external:
      name: nat

