version: '3'

services:
  convergencebackend:
    image: convergencebackend
    build:
      context: .
      dockerfile: ConvergenceBackend/Dockerfile

  tradingbackend:
    image: tradingbackend
    build:
      context: .
      dockerfile: TradingBackend/Dockerfile

