/*
 * TradingView REST API Specification for Brokers
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * 
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{         /// <summary>
        /// Constant. Set it to \"brokerSymbol\".
        /// </summary>
        /// <value>Constant. Set it to \"brokerSymbol\".</value>
        public enum SingleField
        { 
            /// <summary>
            /// Enum BrokerSymbolEnum for brokerSymbol
            /// </summary>
            [EnumMember(Value = "brokerSymbol")]
            BrokerSymbolEnum = 1
        }
}
