/*
 * TradingView REST API Specification for Brokers
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * 
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// Map of Broker instrument name to TradingView instrument name
    /// </summary>
    [DataContract]
    public partial class SingleMapping : IEquatable<SingleMapping>
    { 
        /// <summary>
        /// An array with the only one string element &amp;ndash; broker symbol name
        /// </summary>
        /// <value>An array with the only one string element &amp;ndash; broker symbol name</value>
        [DataMember(Name="f")]
        public List<string> F { get; set; }

        /// <summary>
        /// TradingView symbol name with prefix (AA:XXXX)
        /// </summary>
        /// <value>TradingView symbol name with prefix (AA:XXXX)</value>
        [DataMember(Name="s")]
        public string S { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SingleMapping {\n");
            sb.Append("  F: ").Append(F).Append("\n");
            sb.Append("  S: ").Append(S).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((SingleMapping)obj);
        }

        /// <summary>
        /// Returns true if SingleMapping instances are equal
        /// </summary>
        /// <param name="other">Instance of SingleMapping to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SingleMapping other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    F == other.F ||
                    F != null &&
                    F.SequenceEqual(other.F)
                ) && 
                (
                    S == other.S ||
                    S != null &&
                    S.Equals(other.S)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (F != null)
                    hashCode = hashCode * 59 + F.GetHashCode();
                    if (S != null)
                    hashCode = hashCode * 59 + S.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(SingleMapping left, SingleMapping right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(SingleMapping left, SingleMapping right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
