/*
 * TradingView REST API Specification for Brokers
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 *
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.Runtime.Serialization;

namespace IO.Swagger.Models
{         /// <summary>
          /// Gets or Sets Status
          /// </summary>
    public enum Status
    {
        /// <summary>
        /// Enum OkEnum for ok
        /// </summary>
        [EnumMember(Value = "ok")]
        OkEnum = 1,

        /// <summary>
        /// Enum ErrorEnum for error
        /// </summary>
        [EnumMember(Value = "error")]
        ErrorEnum = 2
    }
}
